import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />

      <main className="flex-grow py-8">
        <div className="container mx-auto px-4 max-w-4xl">
          <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>

          <div className="bg-white rounded-lg shadow p-8">
            <div className="prose max-w-none">
              <p className="mb-6"><strong>Last updated:</strong> March 17, 2026</p>

              <p className="mb-6">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p>

              <h2 className="text-2xl font-bold mt-8 mb-4">Interpretation and Definitions</h2>
              <h3 className="text-xl font-semibold mt-6 mb-3">Interpretation</h3>
              <p className="mb-6">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">Definitions</h3>
              <p className="mb-2"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
              <p className="mb-2"><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to FaresMatch.</p>
              <p className="mb-2"><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
              <p className="mb-2"><strong>Country</strong> refers to: New York, United States</p>
              <p className="mb-2"><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
              <p className="mb-2"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
              <p className="mb-2"><strong>Service</strong> refers to the Website.</p>
              <p className="mb-2"><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
              <p className="mb-2"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
              <p className="mb-2"><strong>Website</strong> refers to FaresMatch, accessible from <a href="https://www.faresmatch.com" className="text-blue-600 hover:underline">https://www.faresmatch.com</a></p>
              <p className="mb-6"><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>

              <h2 className="text-2xl font-bold mt-8 mb-4">Collecting and Using Your Personal Data</h2>
              <h3 className="text-xl font-semibold mt-6 mb-3">Types of Data Collected</h3>
              <h4 className="text-lg font-medium mt-4 mb-2">Personal Data</h4>
              <p className="mb-6">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="list-disc pl-6 mb-6">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Usage Data</li>
              </ul>

              <h4 className="text-lg font-medium mt-4 mb-2">Usage Data</h4>
              <p className="mb-6">
                Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>

              <h4 className="text-lg font-medium mt-4 mb-2">Tracking Technologies and Cookies</h4>
              <p className="mb-2">
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
              </p>
              <p className="mb-6">
                You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.
              </p>

              <h2 className="text-2xl font-bold mt-8 mb-4">Use of Your Personal Data</h2>
              <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
              <ul className="list-disc pl-6 mb-6">
                <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
                <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
              </ul>

              <h2 className="text-2xl font-bold mt-8 mb-4">Retention of Your Personal Data</h2>
              <p className="mb-6">
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
              </p>

              <h2 className="text-2xl font-bold mt-8 mb-4">Transfer of Your Personal Data</h2>
              <p className="mb-6">
                Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
              </p>

              <h2 className="text-2xl font-bold mt-8 mb-4">Disclosure of Your Personal Data</h2>
              <h3 className="text-xl font-semibold mt-6 mb-3">Business Transactions</h3>
              <p className="mb-6">
                If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">Law enforcement</h3>
              <p className="mb-6">
                Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
              </p>

              <h3 className="text-xl font-semibold mt-6 mb-3">Other legal requirements</h3>
              <p className="mb-6">
                The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
              </p>
              <ul className="list-disc pl-6 mb-6">
                <li>Comply with a legal obligation</li>
                <li>Protect and defend the rights or property of the Company</li>
                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>Protect the personal safety of Users of the Service or the public</li>
                <li>Protect against legal liability</li>
              </ul>

              <h2 className="text-2xl font-bold mt-8 mb-4">Security of Your Personal Data</h2>
              <p className="mb-6">
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
              </p>

              <h2 className="text-2xl font-bold mt-8 mb-4">Children's Privacy</h2>
              <p className="mb-6">
                Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
              </p>

              <h2 className="text-2xl font-bold mt-8 mb-4">Links to Other Websites</h2>
              <p className="mb-6">
                Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
              </p>

              <h2 className="text-2xl font-bold mt-8 mb-4">Changes to this Privacy Policy</h2>
              <p className="mb-6">
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
              </p>

              <h2 className="text-2xl font-bold mt-8 mb-4">Contact Us</h2>
              <p className="mb-6">
                If you have any questions about this Privacy Policy, You can contact us:
              </p>
              <ul className="list-disc pl-6 mb-6">
                <li>By email: privacy@faresmatch.com</li>
                <li>By phone: +1-800-918-3039</li>
                <li>By visiting this page on our website: https://www.faresmatch.com/contact</li>
              </ul>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}