// Mock data for car rentals
export const mockCars = [
  {
    id: "1",
    provider: "Hertz",
    name: "Toyota Camry",
    category: "Intermediate",
    seats: 5,
    bags: 2,
    transmission: "Automatic",
    fuelPolicy: "Full to Full",
    pricePerDay: 45,
    image: "/placeholder-car.jpg",
    rating: 4.3,
    reviewCount: 240,
    features: ["AC", "GPS", "Bluetooth"],
    available: true,
  },
  {
    id: "2",
    provider: "Avis",
    name: "Honda Civic",
    category: "Economy",
    seats: 5,
    bags: 2,
    transmission: "Manual",
    fuelPolicy: "Full to Full",
    pricePerDay: 35,
    image: "/placeholder-car.jpg",
    rating: 4.1,
    reviewCount: 180,
    features: ["AC"],
    available: true,
  },
  {
    id: "3",
    provider: "Enterprise",
    name: "Ford Escape",
    category: "SUV",
    seats: 5,
    bags: 3,
    transmission: "Automatic",
    fuelPolicy: "Full to Full",
    pricePerDay: 60,
    image: "/placeholder-car.jpg",
    rating: 4.5,
    reviewCount: 320,
    features: ["AC", "GPS", "Bluetooth", "Backup Camera"],
    available: true,
  },
  {
    id: "4",
    provider: "Budget",
    name: "Nissan Versa",
    category: "Compact",
    seats: 5,
    bags: 2,
    transmission: "Automatic",
    fuelPolicy: "Full to Full",
    pricePerDay: 38,
    image: "/placeholder-car.jpg",
    rating: 3.9,
    reviewCount: 150,
    features: ["AC", "Bluetooth"],
    available: true,
  },
  {
    id: "5",
    provider: "Alamo",
    name: "Chevrolet Silverado",
    category: "Pickup",
    seats: 6,
    bags: 2,
    transmission: "Automatic",
    fuelPolicy: "Full to Full",
    pricePerDay: 75,
    image: "/placeholder-car.jpg",
    rating: 4.6,
    reviewCount: 95,
    features: ["AC", "GPS", "Bluetooth", "4WD"],
    available: true,
  },
  {
    id: "6",
    provider: "Thrifty",
    name: "BMW 3 Series",
    category: "Premium",
    seats: 5,
    bags: 2,
    transmission: "Automatic",
    fuelPolicy: "Full to Full",
    pricePerDay: 85,
    image: "/placeholder-car.jpg",
    rating: 4.7,
    reviewCount: 78,
    features: ["AC", "GPS", "Bluetooth", "Leather Seats", "Sunroof"],
    available: true,
  },
];

// Mock data for car filters
export const mockCarFilters = {
  carType: [
    { name: "Economy", count: 12 },
    { name: "Compact", count: 8 },
    { name: "Intermediate", count: 15 },
    { name: "Standard", count: 10 },
    { name: "Full-size", count: 7 },
    { name: "SUV", count: 20 },
    { name: "Luxury", count: 5 },
    { name: "Pickup", count: 8 },
  ],
  supplier: [
    { name: "Hertz", count: 18 },
    { name: "Avis", count: 15 },
    { name: "Enterprise", count: 22 },
    { name: "Budget", count: 14 },
    { name: "Alamo", count: 10 },
    { name: "National", count: 8 },
    { name: "Thrifty", count: 6 },
  ],
  price: {
    min: 25,
    max: 150,
    currentMin: 35,
    currentMax: 85,
  },
  fuelPolicy: [
    { name: "Full to Full", count: 52 },
    { name: "Pre-pay", count: 18 },
  ],
  transmission: [
    { name: "Automatic", count: 58 },
    { name: "Manual", count: 12 },
  ],
};