// Mock data for hotels
export const mockHotels = [
  {
    id: "1",
    name: "Grand Plaza Hotel",
    rating: 4.5,
    reviewCount: 1200,
    pricePerNight: 189,
    originalPrice: 220,
    image: "/placeholder-hotel.jpg",
    location: "Downtown, New York",
    distanceFromCenter: "0.2 mi",
    amenities: ["WiFi", "Pool", "Gym", "Restaurant", "Spa"],
    description: "Luxury hotel in the heart of Manhattan with stunning city views.",
  },
  {
    id: "2",
    name: "Sunset Beach Resort",
    rating: 4.7,
    reviewCount: 850,
    pricePerNight: 249,
    originalPrice: 299,
    image: "/placeholder-hotel.jpg",
    location: "Miami Beach, Miami",
    distanceFromCenter: "0.1 mi",
    amenities: ["WiFi", "Beach Access", "Pool", "Spa", "Restaurant"],
    description: "Oceanfront resort with private beach access and multiple dining options.",
  },
  {
    id: "3",
    name: "Mountain View Lodge",
    rating: 4.3,
    reviewCount: 640,
    pricePerNight: 159,
    originalPrice: 199,
    image: "/placeholder-hotel.jpg",
    location: "Downtown, Denver",
    distanceFromCenter: "0.5 mi",
    amenities: ["WiFi", "Free Parking", "Gym", "Restaurant"],
    description: "Cozy lodge with mountain views and easy access to downtown Denver.",
  },
  {
    id: "4",
    name: "City Center Inn",
    rating: 4.0,
    reviewCount: 920,
    pricePerNight: 129,
    originalPrice: 159,
    image: "/placeholder-hotel.jpg",
    location: "Financial District, San Francisco",
    distanceFromCenter: "0.3 mi",
    amenities: ["WiFi", "Business Center", "Restaurant"],
    description: "Modern hotel with convenient location in the financial district.",
  },
  {
    id: "5",
    name: "Luxury Suites & Spa",
    rating: 4.8,
    reviewCount: 1400,
    pricePerNight: 349,
    originalPrice: 399,
    image: "/placeholder-hotel.jpg",
    location: "Beverly Hills, Los Angeles",
    distanceFromCenter: "0.8 mi",
    amenities: ["WiFi", "Spa", "Pool", "Gym", "Restaurant", "Concierge"],
    description: "5-star luxury experience with world-class amenities.",
  },
  {
    id: "6",
    name: "Budget Stay Motel",
    rating: 3.8,
    reviewCount: 420,
    pricePerNight: 79,
    originalPrice: 99,
    image: "/placeholder-hotel.jpg",
    location: "Outskirts, Las Vegas",
    distanceFromCenter: "3.2 mi",
    amenities: ["WiFi", "Free Parking"],
    description: "Affordable option with clean rooms and basic amenities.",
  },
];

// Mock data for hotel filters
export const mockHotelFilters = {
  price: {
    min: 50,
    max: 500,
    currentMin: 79,
    currentMax: 349,
  },
  starRating: [
    { stars: 5, count: 12 },
    { stars: 4, count: 28 },
    { stars: 3, count: 15 },
    { stars: 2, count: 8 },
    { stars: 1, count: 3 },
  ],
  guestRating: [
    { label: "Wonderful 4.5+", count: 18 },
    { label: "Very Good 4+", count: 25 },
    { label: "Good 3.5+", count: 12 },
  ],
  amenities: [
    { name: "Free WiFi", count: 42 },
    { name: "Pool", count: 28 },
    { name: "Gym", count: 24 },
    { name: "Spa", count: 15 },
    { name: "Restaurant", count: 38 },
    { name: "Free Parking", count: 22 },
    { name: "Beach Access", count: 8 },
  ],
  propertyType: [
    { name: "Resort", count: 15 },
    { name: "Hotel", count: 32 },
    { name: "Motel", count: 8 },
    { name: "Apartment", count: 12 },
    { name: "Boutique", count: 9 },
  ],
  neighborhood: [
    { name: "Downtown", count: 18 },
    { name: "Beachfront", count: 7 },
    { name: "Airport", count: 5 },
    { name: "Near Shopping", count: 12 },
    { name: "City Center", count: 22 },
  ],
};

// Mock data for room types
export const mockRoomTypes = [
  {
    id: "101",
    hotelId: "1",
    name: "Deluxe King Room",
    description: "Spacious room with king-size bed and city views",
    price: 189,
    amenities: ["WiFi", "Mini Bar", "Coffee Maker", "Air Conditioning"],
    image: "/placeholder-room.jpg",
    availability: 5,
  },
  {
    id: "102",
    hotelId: "1",
    name: "Executive Suite",
    description: "Luxurious suite with separate living area",
    price: 299,
    amenities: ["WiFi", "Kitchenette", "Balcony", "Jacuzzi"],
    image: "/placeholder-room.jpg",
    availability: 2,
  },
  {
    id: "103",
    hotelId: "1",
    name: "Standard Twin Room",
    description: "Comfortable room with two twin beds",
    price: 159,
    amenities: ["WiFi", "Desk", "Air Conditioning"],
    image: "/placeholder-room.jpg",
    availability: 8,
  },
];