// Mock data for flights
export const mockFlights = [
  {
    id: "1",
    airline: "American Airlines",
    airlineCode: "AA",
    flightNumber: "AA1234",
    departureTime: "08:30",
    arrivalTime: "11:45",
    departureAirport: "JFK",
    arrivalAirport: "LAX",
    duration: "6h 15m",
    stops: 0,
    price: 349,
    basePrice: 299,
    taxes: 50,
    aircraft: "Boeing 737",
    amenities: ["Entertainment", "Snacks"],
  },
  {
    id: "2",
    airline: "Delta Airlines",
    airlineCode: "DL",
    flightNumber: "DL5678",
    departureTime: "10:15",
    arrivalTime: "13:50",
    departureAirport: "JFK",
    arrivalAirport: "LAX",
    duration: "6h 35m",
    stops: 0,
    price: 379,
    basePrice: 329,
    taxes: 50,
    aircraft: "Airbus A321",
    amenities: ["Entertainment", "Meal"],
  },
  {
    id: "3",
    airline: "United Airlines",
    airlineCode: "UA",
    flightNumber: "UA9012",
    departureTime: "14:20",
    arrivalTime: "17:55",
    departureAirport: "JFK",
    arrivalAirport: "LAX",
    duration: "6h 35m",
    stops: 0,
    price: 359,
    basePrice: 309,
    taxes: 50,
    aircraft: "Boeing 777",
    amenities: ["Entertainment", "Premium Snacks"],
  },
  {
    id: "4",
    airline: "JetBlue",
    airlineCode: "B6",
    flightNumber: "B63456",
    departureTime: "16:45",
    arrivalTime: "20:20",
    departureAirport: "JFK",
    arrivalAirport: "LAX",
    duration: "6h 35m",
    stops: 1,
    price: 329,
    basePrice: 279,
    taxes: 50,
    aircraft: "Airbus A320",
    amenities: ["Entertainment"],
  },
  {
    id: "5",
    airline: "Spirit Airlines",
    airlineCode: "NK",
    flightNumber: "NK7890",
    departureTime: "19:10",
    arrivalTime: "22:45",
    departureAirport: "JFK",
    arrivalAirport: "LAX",
    duration: "6h 35m",
    stops: 0,
    price: 289,
    basePrice: 239,
    taxes: 50,
    aircraft: "Airbus A320",
    amenities: [],
  },
];

// Mock data for airports
export const mockAirports = [
  { code: "JFK", name: "John F. Kennedy International Airport", city: "New York", country: "USA" },
  { code: "LAX", name: "Los Angeles International Airport", city: "Los Angeles", country: "USA" },
  { code: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "USA" },
  { code: "DFW", name: "Dallas/Fort Worth International Airport", city: "Dallas", country: "USA" },
  { code: "MIA", name: "Miami International Airport", city: "Miami", country: "USA" },
  { code: "SFO", name: "San Francisco International Airport", city: "San Francisco", country: "USA" },
  { code: "SEA", name: "Seattle-Tacoma International Airport", city: "Seattle", country: "USA" },
  { code: "ATL", name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta", country: "USA" },
  { code: "LHR", name: "London Heathrow Airport", city: "London", country: "UK" },
  { code: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France" },
];

// Mock data for airlines
export const mockAirlines = [
  { code: "AA", name: "American Airlines", alliance: "OneWorld" },
  { code: "DL", name: "Delta Airlines", alliance: "SkyTeam" },
  { code: "UA", name: "United Airlines", alliance: "Star Alliance" },
  { code: "B6", name: "JetBlue", alliance: null },
  { code: "NK", name: "Spirit Airlines", alliance: null },
  { code: "F9", name: "Frontier Airlines", alliance: null },
  { code: "AS", name: "Alaska Airlines", alliance: "OneWorld" },
  { code: "HA", name: "Hawaiian Airlines", alliance: null },
];

// Mock data for filters
export const mockFilters = {
  airlines: [
    { code: "AA", name: "American Airlines", count: 12 },
    { code: "DL", name: "Delta Airlines", count: 8 },
    { code: "UA", name: "United Airlines", count: 10 },
    { code: "B6", name: "JetBlue", count: 6 },
    { code: "NK", name: "Spirit Airlines", count: 4 },
  ],
  stops: [
    { label: "Nonstop", count: 15, value: "0" },
    { label: "1 Stop", count: 8, value: "1" },
    { label: "2+ Stops", count: 3, value: "2+" },
  ],
  times: [
    { label: "Early Morning (00:00-06:00)", count: 5 },
    { label: "Morning (06:00-12:00)", count: 12 },
    { label: "Afternoon (12:00-18:00)", count: 8 },
    { label: "Evening (18:00-24:00)", count: 3 },
  ],
  alliances: [
    { name: "SkyTeam", count: 7 },
    { name: "Star Alliance", count: 9 },
    { name: "OneWorld", count: 8 },
  ],
};

// Mock data for price calendar
export const mockPriceCalendar = [
  { date: "2023-06-01", price: 350 },
  { date: "2023-06-02", price: 320 },
  { date: "2023-06-03", price: 380 },
  { date: "2023-06-04", price: 420 },
  { date: "2023-06-05", price: 300 },
  { date: "2023-06-06", price: 310 },
  { date: "2023-06-07", price: 290 },
  { date: "2023-06-08", price: 340 },
  { date: "2023-06-09", price: 360 },
  { date: "2023-06-10", price: 410 },
  { date: "2023-06-11", price: 330 },
  { date: "2023-06-12", price: 370 },
  { date: "2023-06-13", price: 280 },
  { date: "2023-06-14", price: 320 },
  { date: "2023-06-15", price: 390 },
  { date: "2023-06-16", price: 400 },
  { date: "2023-06-17", price: 420 },
  { date: "2023-06-18", price: 310 },
  { date: "2023-06-19", price: 295 },
  { date: "2023-06-20", price: 330 },
  { date: "2023-06-21", price: 350 },
  { date: "2023-06-22", price: 380 },
  { date: "2023-06-23", price: 410 },
  { date: "2023-06-24", price: 340 },
  { date: "2023-06-25", price: 300 },
  { date: "2023-06-26", price: 285 },
  { date: "2023-06-27", price: 320 },
  { date: "2023-06-28", price: 360 },
  { date: "2023-06-29", price: 390 },
  { date: "2023-06-30", price: 430 },
];