// Mock data for vacation packages
export const mockPackages = [
  {
    id: "1",
    name: "Hawaii Paradise Getaway",
    destination: "Hawaii",
    duration: 7,
    pricePerPerson: 1299,
    originalPrice: 1599,
    image: "/placeholder-vacation.jpg",
    rating: 4.7,
    reviewCount: 245,
    inclusions: ["Flight", "Hotel", "Car Rental", "Breakfast"],
    exclusions: ["Meals", "Activities"],
    provider: "Hawaii Travel Co.",
    description: "7-day package to the beautiful Hawaiian islands with luxury accommodations.",
    availableDates: ["2023-06-01", "2023-06-15", "2023-07-01", "2023-07-15"],
  },
  {
    id: "2",
    name: "European Cultural Tour",
    destination: "Europe",
    duration: 14,
    pricePerPerson: 2199,
    originalPrice: 2699,
    image: "/placeholder-vacation.jpg",
    rating: 4.5,
    reviewCount: 187,
    inclusions: ["Flight", "Hotels", "Train Pass", "City Tours"],
    exclusions: ["Lunch", "Dinner", "Airport Transfers"],
    provider: "Euro Explorer",
    description: "Two-week tour through France, Italy, and Spain.",
    availableDates: ["2023-05-01", "2023-05-15", "2023-06-01", "2023-06-15"],
  },
  {
    id: "3",
    name: "Caribbean Cruise",
    destination: "Caribbean",
    duration: 7,
    pricePerPerson: 899,
    originalPrice: 1199,
    image: "/placeholder-vacation.jpg",
    rating: 4.6,
    reviewCount: 320,
    inclusions: ["Cruise", "All Meals", "Port Fees", "Entertainment"],
    exclusions: ["Excursions", "Drinks", "Spa Services"],
    provider: "Caribbean Cruises",
    description: "7-night cruise to Caribbean islands with stops at multiple ports.",
    availableDates: ["2023-04-01", "2023-04-15", "2023-05-01", "2023-05-15"],
  },
  {
    id: "4",
    name: "New York City Break",
    destination: "New York",
    duration: 5,
    pricePerPerson: 799,
    originalPrice: 999,
    image: "/placeholder-vacation.jpg",
    rating: 4.4,
    reviewCount: 156,
    inclusions: ["Flight", "Hotel", "Metro Pass", "Broadway Show"],
    exclusions: ["Meals", "Attractions"],
    provider: "Big Apple Tours",
    description: "5-day city break in the Big Apple with iconic sights and shows.",
    availableDates: ["2023-04-10", "2023-04-24", "2023-05-08", "2023-05-22"],
  },
  {
    id: "5",
    name: "Alaska Adventure",
    destination: "Alaska",
    duration: 10,
    pricePerPerson: 1899,
    originalPrice: 2299,
    image: "/placeholder-vacation.jpg",
    rating: 4.8,
    reviewCount: 98,
    inclusions: ["Flight", "Hotels", "Tours", "Meals"],
    exclusions: ["Alcohol", "Gratuities"],
    provider: "Alaska Expeditions",
    description: "10-day adventure through Alaska's stunning landscapes and wildlife.",
    availableDates: ["2023-06-01", "2023-06-20", "2023-07-05", "2023-07-20"],
  },
  {
    id: "6",
    name: "Mexico Beach Resort",
    destination: "Cancun",
    duration: 7,
    pricePerPerson: 1099,
    originalPrice: 1399,
    image: "/placeholder-vacation.jpg",
    rating: 4.3,
    reviewCount: 192,
    inclusions: ["Flight", "All-Inclusive Resort", "Airport Transfer"],
    exclusions: ["Excursions", "Premium Drinks"],
    provider: "Sun & Sea Vacations",
    description: "All-inclusive 7-day resort stay with private beach access.",
    availableDates: ["2023-04-01", "2023-04-15", "2023-05-01", "2023-05-15"],
  },
];

// Mock data for package filters
export const mockPackageFilters = {
  duration: [
    { label: "3-5 days", count: 8 },
    { label: "6-9 days", count: 15 },
    { label: "10-14 days", count: 12 },
    { label: "15+ days", count: 3 },
  ],
  price: {
    min: 200,
    max: 5000,
    currentMin: 799,
    currentMax: 2199,
  },
  destinationType: [
    { name: "Beach", count: 15 },
    { name: "City", count: 10 },
    { name: "Adventure", count: 8 },
    { name: "Cruise", count: 5 },
    { name: "Cultural", count: 12 },
  ],
  rating: [
    { label: "Wonderful 4.5+", count: 18 },
    { label: "Very Good 4+", count: 22 },
    { label: "Good 3.5+", count: 8 },
  ],
};